# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-05 14:16
from __future__ import unicode_literals

import data_extraction.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Climate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(choices=[('UK', 'UK'), ('England', 'England'), ('Wales\t', 'Wales'), ('Scotland', 'Scotland')], max_length=8)),
                ('max_temp', models.FileField(blank=True, null=True, upload_to=data_extraction.models.get_file_path)),
                ('min_temp', models.FileField(blank=True, null=True, upload_to='')),
                ('mean_temp', models.FileField(blank=True, null=True, upload_to='')),
                ('sunshine', models.FileField(blank=True, null=True, upload_to='')),
                ('rainfall', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
