# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-05 16:54
from __future__ import unicode_literals

import data_extraction.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_extraction', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='climate',
            name='mean_temp',
            field=models.FileField(blank=True, null=True, upload_to=data_extraction.models.get_file_path),
        ),
        migrations.AlterField(
            model_name='climate',
            name='min_temp',
            field=models.FileField(blank=True, null=True, upload_to=data_extraction.models.get_file_path),
        ),
        migrations.AlterField(
            model_name='climate',
            name='rainfall',
            field=models.FileField(blank=True, null=True, upload_to=data_extraction.models.get_file_path),
        ),
        migrations.AlterField(
            model_name='climate',
            name='region',
            field=models.CharField(choices=[('UK', 'UK'), ('England', 'England'), ('Wales\t', 'Wales'), ('Scotland', 'Scotland')], max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='climate',
            name='sunshine',
            field=models.FileField(blank=True, null=True, upload_to=data_extraction.models.get_file_path),
        ),
    ]
