# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-05 16:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_extraction', '0002_auto_20170805_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='climate',
            name='region',
            field=models.CharField(choices=[('UK', 'UK'), ('England', 'England'), ('Wales\t', 'Wales'), ('Scotland', 'Scotland')], max_length=8),
        ),
    ]
