# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-07 11:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_extraction', '0003_auto_20170805_1656'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClimateData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_id', models.IntegerField(blank=True, null=True)),
                ('Year', models.CharField(blank=True, max_length=10, null=True)),
                ('JAN', models.CharField(blank=True, max_length=10, null=True)),
                ('FEB', models.CharField(blank=True, max_length=10, null=True)),
                ('MAR', models.CharField(blank=True, max_length=10, null=True)),
                ('APR', models.CharField(blank=True, max_length=10, null=True)),
                ('MAY', models.CharField(blank=True, max_length=10, null=True)),
                ('JUN', models.CharField(blank=True, max_length=10, null=True)),
                ('JUL', models.CharField(blank=True, max_length=10, null=True)),
                ('AUG', models.CharField(blank=True, max_length=10, null=True)),
                ('SEP', models.CharField(blank=True, max_length=10, null=True)),
                ('OCT', models.CharField(blank=True, max_length=10, null=True)),
                ('NOV', models.CharField(blank=True, max_length=10, null=True)),
                ('DEC', models.CharField(blank=True, max_length=10, null=True)),
                ('WIN', models.CharField(blank=True, max_length=10, null=True)),
                ('SPR', models.CharField(blank=True, max_length=10, null=True)),
                ('SUM', models.CharField(blank=True, max_length=10, null=True)),
                ('AUT', models.CharField(blank=True, max_length=10, null=True)),
                ('ANN', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
    ]
