# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-07 12:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_extraction', '0005_auto_20170807_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='climatedata',
            name='file_id',
            field=models.CharField(blank=True, max_length=1000000, null=True),
        ),
    ]
